Support traversables inside `in` operator
hoaproject/Ruler pull request #113
Opened 2018-01-01 22:55 UTC by ostrolucky

2018-01-02 14:57 UTC, Pierozi submitted a review, later dismissed
Using foreach looks fine to me, in this case the performance should be similar.

2018-01-02 14:57 UTC, Pierozi commented on Visitor/Asserter.php
> +                if ($a == $element) {
Could you use strict equality please.

2018-01-02 15:56 UTC, ostrolucky commented on Visitor/Asserter.php
> +                if ($a == $element) {
I can, but previous in_array construct didn't use strict check either, so this will be BC break. Do you still want it?

2018-01-03 08:00 UTC, Pierozi commented on Visitor/Asserter.php
> +                if ($a == $element) {
Good point, but guess it should have been strict in first place, @Hywan, @vonglasow thoughts?

2018-01-03 18:18 UTC, ostrolucky commented on Visitor/Asserter.php
> +                if ($a == $element) {
IMHO non-strict check is better fit here. 

- No BC break. 
- Consistent with symfony expression language. 
- Easier to understand for users of your DSL (they don't understand concept of types, they won't understand why `'1'` doesn't match `1`). 
- Keeps working with enum objects and cloned objects. That's common pitfall with strict checks..

2018-01-04 09:12 UTC, stephpy commented on Visitor/Asserter.php
> +        $this->setOperator('in',  function ($a, $b) {
IMHO we still have to make a check:

```
if(false === is_array( $b ) && !$b instanceof Traversable ) {
  throw new \InvalidArgumentException(....
}
```

2018-01-04 09:14 UTC, stephpy commented on Visitor/Asserter.php
> +                if ($a == $element) {
To keep BC, i'm agree.
Anyway, if somebody want a strict check, he just has to create a new operator.

2018-01-04 09:16 UTC, stephpy commented on Visitor/Asserter.php
> +                if ($a == $element) {
@Pierozi unfortunately PHP `in_array` function is not strict at all.

```
var_dump(in_array(0, ['foo'])); // true
```

2018-01-04 10:36 UTC, ostrolucky commented on Visitor/Asserter.php
> +                if ($a == $element) {
Here's my stackoverflow question regarding this https://stackoverflow.com/questions/43276251/make-in-array-not-convert-between-numeric-and-alpha-values/48083328#48083328. Might be worthwile to replace current algorithm with array_intersect + iterator_to_array combo

2018-01-04 10:45 UTC, ostrolucky commented on Visitor/Asserter.php
> +        $this->setOperator('in',  function ($a, $b) {
Well similar error would be produced by PHP automatically during foreach call, no need to do it ourselves. But will do anyway.

2018-01-05 19:27 UTC, jubianchi approved these changes

2018-01-08 14:57 UTC, Hywan requested changes

2018-01-08 14:57 UTC, Hywan commented on Test/Unit/Visitor/Asserter.php
> +        $this->_case_boolean_operator('in', [7, [1, 3, 5, 7, 9]], true);
This test case now contains 2 test cases. Please, split it :-).

2018-01-08 14:57 UTC, Hywan commented on Test/Unit/Visitor/Asserter.php
> +        $this->_case_boolean_operator('in', [42, [1, 3, 5, 7, 9]], false);
Same, please split the test case.

2018-01-08 14:57 UTC, Hywan commented on Visitor/Asserter.php
> +                throw new \InvalidArgumentException(sprintf('Expect iterable, got %s', get_class($b)));
Please throw a [`Hoa\Ruler\Exception\Asserter`](https://github.com/hoaproject/Ruler/blob/master/Exception/Asserter.php) instance.

2018-01-08 14:57 UTC, Hywan commented on Visitor/Asserter.php
> +        $this->setOperator('in',  function ($a, $b) {
Why not using the `iterable` type hint?

2018-01-08 14:57 UTC, Hywan commented
Thanks for the PR!

2018-01-08 15:03 UTC, ostrolucky commented on Visitor/Asserter.php
> +        $this->setOperator('in',  function ($a, $b) {
you support PHP 5.6

2018-01-08 15:05 UTC, ostrolucky commented on Test/Unit/Visitor/Asserter.php
> +        $this->_case_boolean_operator('in', [7, [1, 3, 5, 7, 9]], true);
It's ok if test case contains multiple asserts. But ok will split.

2018-01-08 19:08 UTC, Hywan commented on Visitor/Asserter.php
> +        $this->setOperator('in',  function ($a, $b) {
We are dropping PHP 5.x support. So go on :-).

2018-01-08 22:42 UTC, ostrolucky commented on Visitor/Asserter.php
> +        $this->setOperator('in',  function ($a, $b) {
Ok but iterable typehint is available since PHP 7.1 only. So can I drop all other versions from travis matrix?

2018-01-16 20:51 UTC, ostrolucky commented
@Hywan No problem! So, how should we go forward with this? Do you want me to typehint to iterable and drop support for PHP < 7.1, or just change the type of exception thrown?

2018-01-22 10:13 UTC, Hywan commented
@ostrolucky We are discussing about merging the `php7` branch into `master`,  so that's it's going to be much easier for you. Sorry for the late reply, I'm back from my paternity leave :-).

2018-02-05 04:09 UTC, ostrolucky commented
All I see on gh is master branch, no php7?

2018-02-05 08:59 UTC, Hywan commented
`php7` has been merged inside `master`.

2022-02-22 20:43 UTC, closed without merging